export class Stage6_Collection {
    constructor(container, gameManager) {
        this.container = container;
        this.gameManager = gameManager;
        this.timeLeft = 60; // 60 seconds
        this.score = 0;
        this.gridSize = 25; // 5x5 grid
        this.activeItems = [];
        this.timerInterval = null;
        this.spawnInterval = null;
    }

    init() {
        this.render();
        this.startTimer();
        this.spawnItems();
    }

    render() {
        this.container.innerHTML = `
      <div class="stage-collection">
        <div class="hud">
          <h1>SAMPLE COLLECTION</h1>
          <div class="timer glow-text" id="timer">60s</div>
          <div class="score">SAMPLES: <span id="score">0</span></div>
        </div>
        
        <div class="collection-grid" id="collection-grid">
          <!-- Grid items generated by JS -->
        </div>
      </div>
    `;

        const style = document.createElement('style');
        style.textContent = `
      .stage-collection {
        width: 100%;
        height: 100%;
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
      }
      .hud {
        margin-bottom: 20px;
        text-align: center;
        display: flex;
        gap: 20px;
        font-size: 1.5rem;
      }
      .collection-grid {
        display: grid;
        grid-template-columns: repeat(5, 1fr);
        gap: 10px;
        width: 60vw;
        max-width: 500px;
        height: 60vw;
        max-height: 500px;
      }
      .collection-item {
        background: rgba(255, 255, 255, 0.05);
        border: 1px solid rgba(255, 255, 255, 0.1);
        cursor: pointer;
        transition: all 0.2s;
        display: flex;
        align-items: center;
        justify-content: center;
        position: relative;
      }
      .collection-item:hover {
        background: rgba(255, 255, 255, 0.1);
      }
      .collection-item.active {
        background: rgba(0, 243, 255, 0.2);
        border-color: var(--neon-cyan);
        box-shadow: 0 0 10px var(--neon-cyan);
      }
      .collection-item.active::after {
        content: '';
        width: 50%;
        height: 50%;
        background: var(--neon-cyan);
        border-radius: 50%;
        animation: pulse-item 1s infinite;
      }
      @keyframes pulse-item {
        0% { transform: scale(0.8); opacity: 0.8; }
        50% { transform: scale(1.1); opacity: 1; }
        100% { transform: scale(0.8); opacity: 0.8; }
      }
    `;
        this.container.appendChild(style);

        this.gridContainer = document.getElementById('collection-grid');
        this.timerEl = document.getElementById('timer');
        this.scoreEl = document.getElementById('score');

        this.generateGrid();
    }

    generateGrid() {
        for (let i = 0; i < this.gridSize; i++) {
            const item = document.createElement('div');
            item.classList.add('collection-item');
            item.dataset.index = i;
            item.addEventListener('click', () => this.handleCollect(item));
            this.gridContainer.appendChild(item);
        }
    }

    startTimer() {
        this.timerInterval = setInterval(() => {
            this.timeLeft--;
            this.timerEl.textContent = `${this.timeLeft}s`;
            if (this.timeLeft <= 0) {
                this.endGame();
            }
        }, 1000);
    }

    spawnItems() {
        // Initial spawn
        this.activateRandomItem();

        // Continuous spawn
        this.spawnInterval = setInterval(() => {
            if (document.querySelectorAll('.collection-item.active').length < 5) {
                this.activateRandomItem();
            }
        }, 500);
    }

    activateRandomItem() {
        const items = document.querySelectorAll('.collection-item:not(.active)');
        if (items.length === 0) return;

        const randomItem = items[Math.floor(Math.random() * items.length)];
        randomItem.classList.add('active');

        // Auto-despawn after some time if not clicked (optional difficulty)
        setTimeout(() => {
            if (randomItem.classList.contains('active')) {
                randomItem.classList.remove('active');
            }
        }, 2000 + Math.random() * 1000);
    }

    handleCollect(item) {
        if (item.classList.contains('active')) {
            item.classList.remove('active');
            this.score++;
            this.scoreEl.textContent = this.score;

            // Visual feedback
            const feedback = document.createElement('div');
            feedback.textContent = '+1';
            feedback.style.position = 'absolute';
            feedback.style.color = 'var(--neon-cyan)';
            feedback.style.pointerEvents = 'none';
            feedback.style.animation = 'float-up 0.5s ease-out forwards';
            item.appendChild(feedback);

            setTimeout(() => feedback.remove(), 500);
        }
    }

    endGame() {
        clearInterval(this.timerInterval);
        clearInterval(this.spawnInterval);
        alert(`MISSION COMPLETE! SAMPLES COLLECTED: ${this.score}`);
        // Reset or loop back to start?
        // For now, reload page or show final screen
        location.reload();
    }

    cleanup() {
        clearInterval(this.timerInterval);
        clearInterval(this.spawnInterval);
    }
}
