export class Stage5_Scanning {
  constructor(container, gameManager) {
    this.container = container;
    this.gameManager = gameManager;
    this.totalSegments = 80;
    this.scannedSegments = 0;
    this.grid = [];
  }

  init() {
    this.render();
    this.attachEvents();
  }

  render() {
    this.container.innerHTML = `
      <div class="stage-scanning">
        <div class="hud">
          <h1>TERRITORY SCANNING</h1>
          <div class="progress-bar-container glow-box">
            <div class="progress-bar" id="scan-progress"></div>
          </div>
          <div class="status-text">SCANNED: <span id="scan-count">0</span>/${this.totalSegments}</div>
        </div>
        
        <div class="grid-container" id="grid-container">
          <!-- Grid items generated by JS -->
        </div>
      </div>
    `;

    const style = document.createElement('style');
    style.textContent = `
      .stage-scanning {
        width: 100%;
        height: 100%;
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
      }
      .hud {
        margin-bottom: 20px;
        text-align: center;
      }
      .progress-bar-container {
        width: 300px;
        height: 20px;
        margin: 10px auto;
        background: rgba(0,0,0,0.5);
      }
      .progress-bar {
        width: 0%;
        height: 100%;
        background-color: var(--neon-cyan);
        box-shadow: 0 0 10px var(--neon-cyan);
        transition: width 0.2s;
      }
      .grid-container {
        display: grid;
        grid-template-columns: repeat(10, 1fr);
        gap: 5px;
        width: 80vw;
        max-width: 600px;
        height: 60vh;
      }
      .grid-item {
        background: rgba(0, 243, 255, 0.1);
        border: 1px solid rgba(0, 243, 255, 0.3);
        cursor: pointer;
        transition: all 0.3s;
        display: flex;
        align-items: center;
        justify-content: center;
        position: relative;
        overflow: hidden;
      }
      .grid-item:hover {
        background: rgba(0, 243, 255, 0.3);
        transform: scale(1.05);
      }
      .grid-item.scanned {
        background: rgba(0, 243, 255, 0.05);
        border-color: var(--neon-magenta);
        cursor: default;
      }
      .grid-item.scanned:hover {
        transform: none;
      }
      .grid-object {
        width: 60%;
        height: 60%;
        background: var(--neon-magenta);
        clip-path: polygon(50% 0%, 0% 100%, 100% 100%); /* Triangle */
        animation: appear 0.5s ease-out;
        box-shadow: 0 0 10px var(--neon-magenta);
      }
      @keyframes appear {
        0% { transform: scale(0); opacity: 0; }
        100% { transform: scale(1); opacity: 1; }
      }
    `;
    this.container.appendChild(style);

    this.gridContainer = document.getElementById('grid-container');
    this.scanProgress = document.getElementById('scan-progress');
    this.scanCount = document.getElementById('scan-count');

    this.generateGrid();
  }

  generateGrid() {
    for (let i = 0; i < this.totalSegments; i++) {
      const item = document.createElement('div');
      item.classList.add('grid-item');
      item.dataset.index = i;
      item.addEventListener('click', () => this.handleScan(item));
      this.gridContainer.appendChild(item);
    }
  }

  handleScan(item) {
    if (item.classList.contains('scanned')) return;

    item.classList.add('scanned');

    // Add object visual
    const object = document.createElement('div');
    object.classList.add('grid-object');
    // Randomize shape slightly
    const shapes = [
      'polygon(50% 0%, 0% 100%, 100% 100%)', // Triangle
      'polygon(50% 0%, 100% 50%, 50% 100%, 0% 50%)', // Diamond
      'circle(50% at 50% 50%)' // Circle
    ];
    object.style.clipPath = shapes[Math.floor(Math.random() * shapes.length)];
    item.appendChild(object);

    this.scannedSegments++;
    this.updateProgress();

    if (this.scannedSegments >= this.totalSegments) {
      setTimeout(() => this.completeStage(), 500);
    }
  }

  updateProgress() {
    const percent = (this.scannedSegments / this.totalSegments) * 100;
    this.scanProgress.style.width = `${percent}%`;
    this.scanCount.textContent = this.scannedSegments;
  }

  completeStage() {
    alert('TERRITORY FULLY SCANNED.');
    this.gameManager.nextStage();
  }

  cleanup() {
    // No specific cleanup needed for DOM elements as container is cleared
  }
}
